root: true
env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - '@react-native-community'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  jsx-quotes:
    - error
    - prefer-single
  quotes:
    - error
    - single
  semi:
    - error
    - never
